@echo off
@REM 代码格式化脚本

@REM 获取执行脚本绝对路径
set ABSOLUTE_SCRIPT_PATH=%~f0
echo "ABSOLUTE_SCRIPT_PATH:%ABSOLUTE_SCRIPT_PATH%"
@REM 获取执行脚本绝对目录
set ABSOLUTE_SCRIPT_DIRECTORY=%~dp0
echo "ABSOLUTE_SCRIPT_DIRECTORY:%ABSOLUTE_SCRIPT_DIRECTORY%"
@REM 获取执行脚本文件名
set SCRIPT_NAME=%~nx0
echo "SCRIPT_NAME:%SCRIPT_NAME%"
@REM 获取执行脚本父级目录名称
set SCRIPT_PARENT_DIRECTORY=%ABSOLUTE_SCRIPT_DIRECTORY:~0,-1%
echo "SCRIPT_PARENT_DIRECTORY:%SCRIPT_PARENT_DIRECTORY%"

@REM 返回执行脚本父级目录
cd "%ABSOLUTE_SCRIPT_DIRECTORY%/.."

echo "isort import"
isort %ABSOLUTE_SCRIPT_DIRECTORY%

echo "black code"
black --line-length=512 %ABSOLUTE_SCRIPT_DIRECTORY%